### ISSUE TITLE
Maven compile error

### ISSUE THREAD

**Issue by indigo423** [unicolet/opennms-events#2]
I cloned the repository and ran the command

```
mvn clean package
```

and got the following compilation error message:

```
events/target/generated-sources/annotations -g -nowarn -target 1.6 -source 1.6 -encoding UTF-8
[INFO] Compiling 2 source files to /root/opennms-events/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] error: error reading /root/.m2/repository/org/elasticsearch/elasticsearch/1.0.0/elasticsearch-1.0.0.jar; error in opening zip file
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure
error: error reading /root/.m2/repository/org/elasticsearch/elasticsearch/1.0.0/elasticsearch-1.0.0.jar; error in opening zip file

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.BuildFailureException: Compilation failure
error: error reading /root/.m2/repository/org/elasticsearch/elasticsearch/1.0.0/elasticsearch-1.0.0.jar; error in opening zip file

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:715)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
error: error reading /root/.m2/repository/org/elasticsearch/elasticsearch/1.0.0/elasticsearch-1.0.0.jar;     error in opening zip file

    at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:729)
    at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at     org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    ... 17 more
```

Java version:

```
javac -version
javac 1.7.0_71
```

Apache maven:

```
mvn --version
Apache Maven 2.2.1 (rdebian-14)
Java version: 1.7.0_71
Java home: /usr/lib/jvm/jdk1.7.0_71/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux" version: "3.13.0-45-generic" arch: "amd64" Family: "unix"
```

I've deleted the .m2/repository directory and tried again with the same error message.

**Comment by unicolet** [comment]
Hi Ronny, good to hear from you!

Works for me with maven 3:

```
 % mvn3 --version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: /home/unicoletti/bin/apache-maven-3.2.3
Java version: 1.6.0_39, vendor: Sun Microsystems Inc.
Java home: /usr/lib/jvm/jdk1.6.0_39/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-34-generic", arch: "i386", family: "unix"
```

Can you upgrade? If you can't I'll look into it, but no promises.

**Comment by indigo423** [comment]
I've installed latest maven 

```
mvn --version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /opt/mvn
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.7.0_71/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-45-generic", arch: "amd64", family: "unix"
```

I deleted the ~/.m2/repository directory and tried again with `mvn clean package` BUILD SUCCESS.
